In [1]:
# Importe numpy como np.

import numpy as np

In [2]:
# Crie uma matriz de 10 zeros.

ma = np.zeros(10)
ma

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Crie uma matriz de 10 ones.

ma2 = np.ones(10)
ma2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# Crie uma matriz de 10 cincos.

ma3 = [5,5,5,5,5,5,5,5,5,5]
arr = np.array(ma3)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
# Crie um Array de inteiros de 10 até 50.

ma4 = np.arange(10,51)
ma4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
# Crie um array de números pares de 10 até 50.

ma5 = np.arange(10,51,2)
ma5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
# Crie uma matriz 3x3 com valores variando de 0 a 8.

ma6 = [[0,1,2],[3,4,5],[6,7,8]]
ma6 = np.array(ma6)
ma6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# crie uma matriz identidade 3x3.

ma7 = np.eye(3)
ma7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# use numpy para gerar números aleatórios entre 0 e 1.

ma8 = np.random.rand(9)
ma8

array([0.63789132, 0.46143113, 0.5629276 , 0.75086913, 0.3826751 ,
       0.41882384, 0.9043526 , 0.54719507, 0.98693737])

In [10]:
# Use numpy para gerar um array de 25 numeros aleatórios tirados de uma distribuição normal.

ma9 = np.random.randn(25)
ma9

array([ 1.65318361, -0.19961444, -0.62928757,  0.58403711,  0.59317946,
       -0.00346047, -0.85850894, -0.10303084,  0.42912008, -0.71693749,
        0.83750712,  2.06287634, -0.69108696,  0.51963818, -0.22257377,
        0.27799242, -0.3484237 , -0.67607895,  0.90485915, -0.46025198,
        0.30515056,  2.7551992 ,  0.93977032, -0.27326916, -0.74880153])

In [11]:
# Crie uma matriz 10x10 que vá por cada casa decimal de 0.01 a 1.

matriz=np.zeros([10,10]).tolist()
for i in range(10):
    for j in range(10):
        matriz[i][j]=(i*10+(j+1))/100
matriz

[[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1],
 [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2],
 [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3],
 [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4],
 [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5],
 [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6],
 [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7],
 [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8],
 [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9],
 [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]]

In [12]:
# Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

ma11 = np.linspace(0,1,20)
ma11

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
# Crie uma matriz 5x5 de 1 a 25.

ma12 = np.arange(1,26).reshape(5,5)
ma12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# Selecione os valores a partir da 3ª linha e 2ª coluna.

ma12[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
# Selecione apenas o elemento 20 do array.

ma12[3,4]

20

In [16]:
# Selecione os elementos da segunda coluna da linha 1 a 3.

ma12[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
# Selecione todos os elementos da ultima linha.

ma12[4:,:]

array([[21, 22, 23, 24, 25]])

In [18]:
# Selecione todos os elementos da penúltima e última linha.

ma12[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
# Obter a soma de todos os elementos do array.

ma12.sum()

325

In [20]:
# Obter o desvio padrão dos elementos do array.

np.std(ma12)

7.211102550927978

In [21]:
# Obter a soma das colunas. O parâmetro axis indica sobre qual eixo (em uma matriz 2d) a operação será feita. axis=0 indica 
# que a soma será feita em todas as linhas de cada coluna ("vertical"). axis=1 indica que a soma será feita em todas as 
# colunas decada linha ("horizontal").

ma12.sum(axis=0)

array([55, 60, 65, 70, 75])